/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheRiseProgramRouteImport } from './routes/the-rise-program'
import { Route as SubmitTestimonialRouteImport } from './routes/submit-testimonial'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SeerahIntroductoryRouteImport } from './routes/seerah-introductory'
import { Route as SeerahDetailedRouteImport } from './routes/seerah-detailed'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BookClubsRouteImport } from './routes/book-clubs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TheRiseProgramRoute = TheRiseProgramRouteImport.update({
  id: '/the-rise-program',
  path: '/the-rise-program',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitTestimonialRoute = SubmitTestimonialRouteImport.update({
  id: '/submit-testimonial',
  path: '/submit-testimonial',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SeerahIntroductoryRoute = SeerahIntroductoryRouteImport.update({
  id: '/seerah-introductory',
  path: '/seerah-introductory',
  getParentRoute: () => rootRouteImport,
} as any)
const SeerahDetailedRoute = SeerahDetailedRouteImport.update({
  id: '/seerah-detailed',
  path: '/seerah-detailed',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookClubsRoute = BookClubsRouteImport.update({
  id: '/book-clubs',
  path: '/book-clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-clubs': typeof BookClubsRoute
  '/bookings': typeof BookingsRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/newsletter': typeof NewsletterRoute
  '/seerah-detailed': typeof SeerahDetailedRoute
  '/seerah-introductory': typeof SeerahIntroductoryRoute
  '/services': typeof ServicesRoute
  '/submit-testimonial': typeof SubmitTestimonialRoute
  '/the-rise-program': typeof TheRiseProgramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-clubs': typeof BookClubsRoute
  '/bookings': typeof BookingsRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/newsletter': typeof NewsletterRoute
  '/seerah-detailed': typeof SeerahDetailedRoute
  '/seerah-introductory': typeof SeerahIntroductoryRoute
  '/services': typeof ServicesRoute
  '/submit-testimonial': typeof SubmitTestimonialRoute
  '/the-rise-program': typeof TheRiseProgramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-clubs': typeof BookClubsRoute
  '/bookings': typeof BookingsRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/newsletter': typeof NewsletterRoute
  '/seerah-detailed': typeof SeerahDetailedRoute
  '/seerah-introductory': typeof SeerahIntroductoryRoute
  '/services': typeof ServicesRoute
  '/submit-testimonial': typeof SubmitTestimonialRoute
  '/the-rise-program': typeof TheRiseProgramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book-clubs'
    | '/bookings'
    | '/contact'
    | '/courses'
    | '/newsletter'
    | '/seerah-detailed'
    | '/seerah-introductory'
    | '/services'
    | '/submit-testimonial'
    | '/the-rise-program'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book-clubs'
    | '/bookings'
    | '/contact'
    | '/courses'
    | '/newsletter'
    | '/seerah-detailed'
    | '/seerah-introductory'
    | '/services'
    | '/submit-testimonial'
    | '/the-rise-program'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book-clubs'
    | '/bookings'
    | '/contact'
    | '/courses'
    | '/newsletter'
    | '/seerah-detailed'
    | '/seerah-introductory'
    | '/services'
    | '/submit-testimonial'
    | '/the-rise-program'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookClubsRoute: typeof BookClubsRoute
  BookingsRoute: typeof BookingsRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  NewsletterRoute: typeof NewsletterRoute
  SeerahDetailedRoute: typeof SeerahDetailedRoute
  SeerahIntroductoryRoute: typeof SeerahIntroductoryRoute
  ServicesRoute: typeof ServicesRoute
  SubmitTestimonialRoute: typeof SubmitTestimonialRoute
  TheRiseProgramRoute: typeof TheRiseProgramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/the-rise-program': {
      id: '/the-rise-program'
      path: '/the-rise-program'
      fullPath: '/the-rise-program'
      preLoaderRoute: typeof TheRiseProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-testimonial': {
      id: '/submit-testimonial'
      path: '/submit-testimonial'
      fullPath: '/submit-testimonial'
      preLoaderRoute: typeof SubmitTestimonialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seerah-introductory': {
      id: '/seerah-introductory'
      path: '/seerah-introductory'
      fullPath: '/seerah-introductory'
      preLoaderRoute: typeof SeerahIntroductoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seerah-detailed': {
      id: '/seerah-detailed'
      path: '/seerah-detailed'
      fullPath: '/seerah-detailed'
      preLoaderRoute: typeof SeerahDetailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-clubs': {
      id: '/book-clubs'
      path: '/book-clubs'
      fullPath: '/book-clubs'
      preLoaderRoute: typeof BookClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookClubsRoute: BookClubsRoute,
  BookingsRoute: BookingsRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  NewsletterRoute: NewsletterRoute,
  SeerahDetailedRoute: SeerahDetailedRoute,
  SeerahIntroductoryRoute: SeerahIntroductoryRoute,
  ServicesRoute: ServicesRoute,
  SubmitTestimonialRoute: SubmitTestimonialRoute,
  TheRiseProgramRoute: TheRiseProgramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
